/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Me
 */
public class currency_convertor extends javax.swing.JFrame {

    /**
     * Creates new form currency_convertor
     */
    public currency_convertor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Dollars");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Pounds");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Dirhans");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Philipino Peso");
        jRadioButton4.setToolTipText("");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Dollars");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Pounds");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Dirhans");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("Philipino Peso");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("Rupees");
        jRadioButton9.setToolTipText("");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("Rupees");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jRadioButton1)
                        .addGap(132, 132, 132)
                        .addComponent(jRadioButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(122, 122, 122)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton3)
                                        .addComponent(jRadioButton4)
                                        .addComponent(jRadioButton10))
                                    .addGap(87, 87, 87))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton2)
                                    .addGap(126, 126, 126)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton8)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel5))
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String s, i;

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
          i = jTextField1.getText();
         
                       if (jRadioButton4.isSelected()) {
        
            jRadioButton8.setEnabled(false);
            
            if (jRadioButton10.isSelected()) {
                  float rn = Float.parseFloat(i);
                       double  rf = rn * 1.48; 
                     jLabel3.setText("rupeelklklklkklklklklklks");
          jLabel4.setText(String.valueOf(rf));
         } 
           
                {    
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
                    jRadioButton9.setEnabled(true);
                        jRadioButton10.setEnabled(true);
                } 
                                  

            
         
        }
                
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
           i = jScroll.getText();  
        float num3 = Float.parseFloat(i);
         double  dhirans =  num3 / 22.87  ; 
         
                      if (jRadioButton3.isSelected()) {
        
            jRadioButton7.setEnabled(false);
         
        } else {
        jRadioButton7.setEnabled(true); // Re-enable it when not selected
    }
                {    jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
                jRadioButton10.setEnabled(true);
                    jRadioButton8.setEnabled(true);
                        jRadioButton9.setEnabled(true);
                } 
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
           i = jTextField1.getText();
        float num2a = Float.parseFloat(i);
         double  p =  num2a / 109.85 ; 
          
                       if (jRadioButton2.isSelected()) {
        
            jRadioButton6.setEnabled(false);
         
        } else {
        jRadioButton6.setEnabled(true); // Re-enable it when not selected
    }
                {  
                    jRadioButton1.setEnabled(true);
            jRadioButton3.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton7.setEnabled(true);
                jRadioButton8.setEnabled(true);
                    jRadioButton9.setEnabled(true);
                        jRadioButton10.setEnabled(true);
                } 
    }//GEN-LAST:event_jRadioButton2ActionPerformed




    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
           i = jTextField1.getText(); 
       
         
                       if (jRadioButton1.isSelected()) {
        
            jRadioButton5.setEnabled(false);
            
         
                          if (jRadioButton9.isSelected()) {
        
                                float num1 = Float.parseFloat(i);
         double  dr = num1 * 83.99 ; 
            jLabel3.setText("Ruppes->");
          jLabel4.setText(String.valueOf(dr));
           
            
         
        }
            
            
            
            
            
            
        } else {
        jRadioButton5.setEnabled(true); // Re-enable it when not selected
    }
                {    
            jRadioButton7.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true)
            jRadioButton10.setEnabled(true);
           
                } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
   i = jTextField1.getText();
      
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
       
                       if (jRadioButton10.isSelected()) {
        
            jRadioButton9.setEnabled(false);
         
        } else {
        jRadioButton9.setEnabled(true); // Re-enable it when not selected
    }
                {    jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true); 
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
               jRadioButton3.setEnabled(true);
                } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
   i = jTextField1.getText(); 
   
                       if (jRadioButton5.isSelected()) {
        
            jRadioButton1.setEnabled(false);
         
        } else {
        jRadioButton1.setEnabled(true); // Re-enable it when not selected
    }  
       {    jRadioButton9.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton10.setEnabled(true);
        } 
     
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
         
        i = jTextField1.getText(); 
         
        
        //  RUPEE 
                       if (jRadioButton1.isSelected()) {
        
            jRadioButton5.setEnabled(false);
            
         
           if (jRadioButton9.isSelected()) {
        
                                float num1 = Float.parseFloat(i);
         double  dr = num1 * 83.99 ; 
            jLabel3.setText("Ruppes->");
          jLabel4.setText(String.valueOf(dr));
           
            
         
        }
            
            
            
            
            
            
        } 
        
        
        
        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
// TODO add your handling code here:
             if (jRadioButton9.isSelected()) {
                   jRadioButton10.setEnabled(false); 
        } else {
        jRadioButton10.setEnabled(true); // Re-enable it when not selected
    }
                { 
              jRadioButton1.setEnabled(true);
             jRadioButton2.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
             jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
             jRadioButton3.setEnabled(true);
            
                } 
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
 String i = jTextField1.getText();
  


     if (jRadioButton8.isSelected()) { 
            jRadioButton4.setEnabled(false);
            if (jRadioButton1.isSelected()) {// dollars
            jRadioButton4.setEnabled(false);
            if (jRadioButton8.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 57.32 ; 
            jLabel3.setText("Peso ->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
            
            else  
                
                      if (jRadioButton9.isSelected()) {// dollars
            jRadioButton4.setEnabled(false);
            if (jRadioButton9.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 0.68 ; 
            jLabel3.setText("Peso ->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
                
      
                 
                 
                 
                 else        if (jRadioButton2.isSelected()) { //  ponds-> 
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 4.80 ; 
            jLabel3.setText("Peso ->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
                 
            
            // peso 
              else        if (jRadioButton4.isSelected()) { //  ponds-> 
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 *  0.064; 
         jLabel3.setText("Peso ->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
            
            
            
            
        } else {
        jRadioButton3.setEnabled(true); // Re-enable it when not selected
    }
                {    jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true); 
            jRadioButton9.setEnabled(true);
            jRadioButton8.setEnabled(true);
             jRadioButton10.setEnabled(true);
           
                } 
                 
          // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
   // Get the text from the text field
       
   
            i = jTextField1.getText();
            
            if (jRadioButton7.isSelected()) { 
            jRadioButton3.setEnabled(false);
            if (jRadioButton1.isSelected()) {// dollars
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 3.67 ; 
            jLabel3.setText("Dihrans->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
            
            else     if (jRadioButton10.isSelected()) { // rupeee -> 
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 0.44 ; 
            jLabel3.setText("Dihrans->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
                 
                 
                 
                 else        if (jRadioButton2.isSelected()) { //  ponds-> 
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 * 4.80 ; 
            jLabel3.setText("Dihrans->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
                 
            
            // peso 
              else        if (jRadioButton4.isSelected()) { //  ponds-> 
            jRadioButton5.setEnabled(false);
            if (jRadioButton7.isSelected()) {
            float num1 = Float.parseFloat(i);
            double  dr = num1 *  0.064; 
            jLabel3.setText("Dihrans->");
            jLabel4.setText(String.valueOf(dr));
            jRadioButton5.setEnabled(false);
        }
        }
            
            
            
            
        } else {
        jRadioButton3.setEnabled(true); // Re-enable it when not selected
    }
                {    jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true); 
            jRadioButton9.setEnabled(true);
            jRadioButton8.setEnabled(true);
             jRadioButton10.setEnabled(true);
           
                } 
                
                
             
     
       
        
            
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
             i = jTextField1.getText();
     
// TODO add your handling code here:
             if (jRadioButton6.isSelected()) {
        
            jRadioButton2.setEnabled(false);
            
                                   if (jRadioButton1.isSelected()) 
                                   {
        
            jRadioButton5.setEnabled(false);
            
         
                          if (jRadioButton6.isSelected()) {
        
                                float num1 = Float.parseFloat(i);
         double  dr = num1 * 0.77 ; 
            jLabel3.setText("Pounds->");
          jLabel4.setText(String.valueOf(dr));
           
            
         
        }
            
            
            
            
            
            
        }
            
         
        } else {
        jRadioButton2.setEnabled(true); // Re-enable it when not selected
    }
                   jRadioButton1.setEnabled(true);
            jRadioButton3.setEnabled(true);
                       jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
           
             jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
             jRadioButton9.setEnabled(true);
            jRadioButton10.setEnabled(true);
                
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency_convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency_convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency_convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency_convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency_convertor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
